---
# tasks file for nginx_installation
- name: Start sshd service for client CentOS
  systemd:
    name: sshd
    state: started
  when: ansible_facts.os_family|lower == 'redhat'
  
- name: Install Epel release to support CentOS
  yum: 
    name: 
    - epel-release
    state: present
  when: ansible_facts.os_family|lower == 'redhat'

- name: Install Nginx Service to Client
  package:
    name: nginx
    state: present
  notify: Start nginx
# - debug:
#     msg: "{{ansible_facts.os_family}}"
