FROM ubuntu:latest

# Install systemd
RUN apt-get update \
    && apt-get install -y systemd openssh-server \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Tell systemd that it's running in a container
ENV container docker

# Avoid systemd errors during build
RUN (cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
  rm -f /lib/systemd/system/multi-user.target.wants/*;\
  rm -f /etc/systemd/system/*.wants/*;\
  rm -f /lib/systemd/system/local-fs.target.wants/*; \
  rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
  rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
  rm -f /lib/systemd/system/basic.target.wants/*;\
  rm -f /lib/systemd/system/anaconda.target.wants/*;

# Set bash as the default shell
# SHELL ["/bin/bash", "-c"]
# Start systemd
EXPOSE 22 80
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh
COPY id_rsa.pub /root/.ssh/authorized_keys

CMD ["/bin/bash", "-c", "service ssh start && /lib/systemd/systemd"]
# CMD ["/usr/sbin/init"]


